"""
GTM qualification policy — MEDDPICC-derived.

Maps Q_* evidence labels → disposition (qualified / nurture / disqualified).

Framework: MEDDPICC (Metrics, Economic Buyer, Decision Criteria, Decision Process,
Identify Pain, Champion, Competition, Paper Process). Public framework; multiple
structured versions at github.com/meddic/meddpicc and notion.so community templates.

Compose with a confidence threshold: low confidence → HIL regardless of policy
verdict. The compose() function implements this gate.

Override targets (for merge step):
  - REQUIRED_FOR_QUALIFIED: set of Q_* label values that must all be present
  - DISQUALIFY_IF: set of conditions that immediately disqualify
  - CONFIDENCE_HIL_THRESHOLD: float, below which route to HIL
"""

from __future__ import annotations

# Evidence labels from gtm_schema.GtmLabel — listed by value string so this
# module stays import-free from the schema (pure policy logic, no model deps).
_BUDGET = "qualification.budget_confirmed"
_AUTHORITY = "qualification.authority_identified"
_NEED = "qualification.need_articulated"
_TIMELINE = "qualification.timeline_stated"

REQUIRED_FOR_QUALIFIED: frozenset[str] = frozenset({_NEED, _AUTHORITY})
STRONG_QUALIFIED: frozenset[str] = frozenset({_BUDGET, _AUTHORITY, _NEED, _TIMELINE})

CONFIDENCE_HIL_THRESHOLD: float = 0.70

_QUALIFIED = "qualified"
_NURTURE = "nurture"
_DISQUALIFIED = "disqualified"
_HIL = "hil"


def disposition(evidence_labels: set[str], confidence: float) -> str:
    """
    Map extracted Q_* evidence labels and confidence to a disposition string.

    Returns one of: 'qualified', 'nurture', 'disqualified', 'hil'.

    Policy (MEDDPICC-derived, generic baseline):
    - Low confidence (<= CONFIDENCE_HIL_THRESHOLD) → 'hil' regardless of evidence.
    - All four MEDDPICC evidence labels present → 'qualified'.
    - REQUIRED_FOR_QUALIFIED (need + authority) present → 'qualified'.
    - Need articulated but missing authority → 'nurture'.
    - Nothing relevant present → 'nurture' (keep in pipeline, do not discard).

    Note: 'disqualified' is reserved for explicit negative signals (no budget
    category, wrong segment, explicit rejection) — the base policy does not
    auto-disqualify from absence of evidence alone. Buyer-specific disqualify
    rules go in 03_overrides/policy_overrides.yaml.

    Source: MEDDPICC framework (public); Clari published qualification rubrics
    (clari.com/blog/meddpicc-sales-methodology).
    """
    if confidence <= CONFIDENCE_HIL_THRESHOLD:
        return _HIL

    has_need = _NEED in evidence_labels
    has_authority = _AUTHORITY in evidence_labels
    has_budget = _BUDGET in evidence_labels
    has_timeline = _TIMELINE in evidence_labels

    if STRONG_QUALIFIED.issubset(evidence_labels):
        return _QUALIFIED

    if REQUIRED_FOR_QUALIFIED.issubset(evidence_labels):
        return _QUALIFIED

    if has_need and has_budget:
        return _QUALIFIED

    if has_need or has_authority:
        return _NURTURE

    return _NURTURE


def compose(
    evidence_labels: set[str],
    confidence: float,
    policy_verdict: str | None = None,
) -> str:
    """
    Compose the policy verdict with the confidence gate.

    If policy_verdict is provided, applies the confidence gate on top:
    low confidence routes to 'hil' regardless of verdict.

    If policy_verdict is None, calls disposition() internally.
    """
    if confidence <= CONFIDENCE_HIL_THRESHOLD:
        return _HIL
    if policy_verdict is not None:
        return policy_verdict
    return disposition(evidence_labels, confidence)


# ============================================================
# CLIENT-SPECIFIC POLICY RULES — generated by schema-forge generate
# ============================================================

# --- Client disqualification rules (from policy_overrides) ---
# DISQUALIFY if: A_TECH_STACK_ITEM not contains 'SAP'
# Rationale: Non-SAP ERP accounts are a hard disqualification. The firm's entire service offering (Joule implementation, BTP AI Core, S/4HANA migration + AI uplift) is SAP-specific. Oracle Fusion, Workday, Dynamics 365, and NetSuite accounts cannot use Joule and cannot become clients regardless of size, budget, or expressed AI interest. Source: 02_icp_interview.md §4 anti-ICP #1.

# DISQUALIFY if: Q_NEED_ARTICULATED is null AND Q_TIMELINE_STATED is null
# Rationale: No named use case AND no stated timeline = SAP tire-kicker / exploratory inquiry. This pattern — interest in "AI in SAP" without a specific process problem or project timeline — is the most common wasted-discovery pattern. The firm uses the test "does the prospect say what SAP process they want to improve and by when?" If both are absent after two discovery sessions, move to 6-month nurture. Source: 04_qualification_interview.md §1 use-case gate, 02_icp_interview.md §4 "no named AI use case after two discovery sessions = tire-kicker."

# DISQUALIFY if: Q_BUDGET_CONFIRMED is null AND Q_TIMELINE_STATED is null AND S_S4_MIGRATION_TIMELINE is null
# Rationale: ECC account with no S/4 roadmap and no pilot budget = multi-year nurture. This is the profile of L1 (energy company, DQ'd after Readiness Assessment): large SAP footprint on ECC 6.0, no funded S/4 migration, no pilot budget. Without an S/4 migration timeline or confirmed budget, the Joule implementation is technically and commercially unviable. Cost: 60 days of discovery time on L1. Do not activate in pipeline; place in 18-month nurture cycle. Source: 02_icp_interview.md §4 anti-ICP #2, 05_failure_modes_interview.md FM-SAP-01.


# --- Client auto-pass rules (from policy_overrides) ---
# AUTO_PASS if: Q_AUTHORITY_IDENTIFIED AND Q_NEED_ARTICULATED AND Q_BUDGET_CONFIRMED AND S_JOULE_INTEREST AND confidence > 0.75
# Rationale: All four qualification gates confirmed at high confidence: executive sponsor (CIO/CFO) engaged, named Joule use case from the end-customer, budget $150k-$500k confirmed or in active procurement, and direct Joule interest (not SAP AE-suggested). This combination predicts high conversion probability based on P1 and P3 deal profiles. P1 had all four confirmed by end of discovery and closed in 14 weeks; P3 had all four confirmed by the first call (peer referral pre-qualified) and closed in 10 weeks. Route to AE for proposal scoping immediately. Source: 04_qualification_interview.md §1 auto-pass criteria, 01_company_overview.md §3 deal economics.

# AUTO_PASS if: S_RISE_ADOPTION AND Q_AUTHORITY_IDENTIFIED AND Q_NEED_ARTICULATED AND confidence > 0.70
# Rationale: RISE with SAP account with identified authority and named need: RISE subscription includes Joule entitlement and BTP credits, meaning there is no infrastructure barrier to a Joule pilot. When the end-customer has RISE confirmed plus an executive sponsor and a named use case, the implementation risk is lower than on-prem and the budget is likely already accounted for in the RISE contract. P2 (retail, $410k, RISE customer) confirms this profile. The confidence threshold is slightly lower (0.70) because RISE itself is a strong signal that reduces technical risk. Route to AE for proposal scoping. Source: 02_icp_interview.md §1 tech-stack signal #1 (RISE = "very high signal").


# --- Client HIL rules (from policy_overrides) ---
# HIL if: S_SAP_FIELD_CO_SELL AND Q_BUDGET_CONFIRMED is null
# Rationale: SAP-field co-sell WITHOUT end-customer budget confirmation: this is the "channel mirage" guard, the most costly qualification failure mode. An SAP AE referral without direct end-customer budget evidence is NOT qualified. Route to Alliances Owner (not AE) to verify budget with the AE and confirm a direct end-customer meeting before activating. Do not route to AE until budget is confirmed — this avoids the L3 pattern (45 days wasted on AE referral with no real budget). SAP AE enthusiasm is a co-sell routing signal, not a qualification signal. Source: 04_qualification_interview.md §3 routing rules, 03_channel_interview.md §2 SAP-field failure mode.

# HIL if: S_SI_PARTNER_INVOLVED AND Q_BUDGET_CONFIRMED is null
# Rationale: SI-partner pull-through WITHOUT prime contract confirmation: Big4 MD relationship without a live program is the "partner mirage" failure mode (FM-SAP-03). Route to SI-Partner Lead to confirm prime contract status and SOW slot. Do not activate in pipeline until prime contract signed or final-stage LOI. Investing delivery capacity in unconfirmed SI-partner pursuits is a high-cost failure mode that occurred twice in the last 12 months. Source: 04_qualification_interview.md §3 routing rules, 03_channel_interview.md §3 SI-partner failure mode.

# HIL if: Q_AUTHORITY_IDENTIFIED AND Q_NEED_ARTICULATED AND S_S4_MIGRATION_TIMELINE AND Q_BUDGET_CONFIRMED is null
# Rationale: Executive sponsor and named use case confirmed, S/4 migration timeline confirmed, but budget not yet confirmed: this account has high intent but the budget process is behind. These accounts often convert within one budget cycle if pursued correctly. Route to AE for direct CFO/CIO budget conversation. Do not move to auto-pass until budget is confirmed — timeline + need without budget is L2 risk profile (manufacturer lost to Accenture because CFO engagement was insufficient). Source: 04_qualification_interview.md §2 (Q_BUDGET_CONFIRMED evidence gate), 02_icp_interview.md §3 L2 deal loss.

# HIL if: S_CLEAN_CORE_INITIATIVE AND S_S4_MIGRATION_TIMELINE AND Q_NEED_ARTICULATED is null
# Rationale: Clean core initiative + S/4 migration timeline but no named use case: this account is on the right technical trajectory but has not yet identified a specific Joule use case. These are high-value nurture accounts — technically ready within 12 months but not yet a buyer. Route to AE for nurture call: goal is to help the prospect identify a high-ROI Joule use case, not to close immediately. FM-SAP-09 notes that accounts in clean core + RISE migration mode are often missed because they don't yet have a named use case. Proactive nurture converts these in 6-12 months. Source: 05_failure_modes_interview.md FM-SAP-09, FM-SAP-07.

