"""
GTM qualification policy — MEDDPICC-derived.

Maps Q_* evidence labels → disposition (qualified / nurture / disqualified).

Framework: MEDDPICC (Metrics, Economic Buyer, Decision Criteria, Decision Process,
Identify Pain, Champion, Competition, Paper Process). Public framework; multiple
structured versions at github.com/meddic/meddpicc and notion.so community templates.

Compose with a confidence threshold: low confidence → HIL regardless of policy
verdict. The compose() function implements this gate.

Override targets (for merge step):
  - REQUIRED_FOR_QUALIFIED: set of Q_* label values that must all be present
  - DISQUALIFY_IF: set of conditions that immediately disqualify
  - CONFIDENCE_HIL_THRESHOLD: float, below which route to HIL
"""

from __future__ import annotations

# Evidence labels from gtm_schema.GtmLabel — listed by value string so this
# module stays import-free from the schema (pure policy logic, no model deps).
_BUDGET = "qualification.budget_confirmed"
_AUTHORITY = "qualification.authority_identified"
_NEED = "qualification.need_articulated"
_TIMELINE = "qualification.timeline_stated"

REQUIRED_FOR_QUALIFIED: frozenset[str] = frozenset({_NEED, _AUTHORITY})
STRONG_QUALIFIED: frozenset[str] = frozenset({_BUDGET, _AUTHORITY, _NEED, _TIMELINE})

CONFIDENCE_HIL_THRESHOLD: float = 0.70

_QUALIFIED = "qualified"
_NURTURE = "nurture"
_DISQUALIFIED = "disqualified"
_HIL = "hil"


def disposition(evidence_labels: set[str], confidence: float) -> str:
    """
    Map extracted Q_* evidence labels and confidence to a disposition string.

    Returns one of: 'qualified', 'nurture', 'disqualified', 'hil'.

    Policy (MEDDPICC-derived, generic baseline):
    - Low confidence (<= CONFIDENCE_HIL_THRESHOLD) → 'hil' regardless of evidence.
    - All four MEDDPICC evidence labels present → 'qualified'.
    - REQUIRED_FOR_QUALIFIED (need + authority) present → 'qualified'.
    - Need articulated but missing authority → 'nurture'.
    - Nothing relevant present → 'nurture' (keep in pipeline, do not discard).

    Note: 'disqualified' is reserved for explicit negative signals (no budget
    category, wrong segment, explicit rejection) — the base policy does not
    auto-disqualify from absence of evidence alone. Buyer-specific disqualify
    rules go in 03_overrides/policy_overrides.yaml.

    Source: MEDDPICC framework (public); Clari published qualification rubrics
    (clari.com/blog/meddpicc-sales-methodology).
    """
    if confidence <= CONFIDENCE_HIL_THRESHOLD:
        return _HIL

    has_need = _NEED in evidence_labels
    has_authority = _AUTHORITY in evidence_labels
    has_budget = _BUDGET in evidence_labels
    has_timeline = _TIMELINE in evidence_labels

    if STRONG_QUALIFIED.issubset(evidence_labels):
        return _QUALIFIED

    if REQUIRED_FOR_QUALIFIED.issubset(evidence_labels):
        return _QUALIFIED

    if has_need and has_budget:
        return _QUALIFIED

    if has_need or has_authority:
        return _NURTURE

    return _NURTURE


def compose(
    evidence_labels: set[str],
    confidence: float,
    policy_verdict: str | None = None,
) -> str:
    """
    Compose the policy verdict with the confidence gate.

    If policy_verdict is provided, applies the confidence gate on top:
    low confidence routes to 'hil' regardless of verdict.

    If policy_verdict is None, calls disposition() internally.
    """
    if confidence <= CONFIDENCE_HIL_THRESHOLD:
        return _HIL
    if policy_verdict is not None:
        return policy_verdict
    return disposition(evidence_labels, confidence)


# ============================================================
# CLIENT-SPECIFIC POLICY RULES — generated by schema-forge generate
# ============================================================

# --- Client disqualification rules (from policy_overrides) ---
# DISQUALIFY if: A_EMPLOYEE_RANGE in ['1-10']
# Rationale: Under 10 employees: insufficient internal infrastructure to absorb a $50k+ engagement. These companies lack a dedicated engineering owner, have immature data practices, and cannot allocate 20% of a technical lead's time to an engagement. Confirmed by regret R-1 (seed-stage, 12 employees — data unready) and multiple explicit disqualifications in the ICP interview. The '1-10' bucket maps to companies under ~10 people.

# DISQUALIFY if: A_FUNDING_STAGE in ['pre_seed', 'seed']
# Rationale: Pre-seed and seed companies routinely fail the three project readiness gates: data readiness (no clean corpus), owner readiness (no named technical owner), infrastructure readiness (no production cloud deployment). Budget also typically insufficient for $50k+ sprint engagements. Confirmed by regret R-1 and ICP interview analysis. Note: bootstrapped companies are NOT disqualified — only VC-backed pre-revenue stages.

# DISQUALIFY if: Q_NEED_ARTICULATED is null AND Q_TIMELINE_STATED is null
# Rationale: 'AI tire-kicker / fake yes' pattern: no articulated need + no stated timeline = exploratory intent, not a real project. Confirmed by failure modes interview §3 and ICP interview §5 (outsider question): "The word 'explore' is a red flag. Real buyers say 'we have X problem and we need to solve it by Y date.'" Both signals absent together is a reliable disqualification trigger.


# --- Client auto-pass rules (from policy_overrides) ---
# AUTO_PASS if: Q_BUDGET_CONFIRMED AND Q_AUTHORITY_IDENTIFIED AND Q_NEED_ARTICULATED AND confidence > 0.75
# Rationale: Three MEDDIC evidence gates confirmed (budget, authority, need) at high confidence. Won-deal analysis: all 5 closed-won deals had all three confirmed by end of discovery. When all three are present with confidence > 0.75, this combination predicts >80% close rate in the deal history reviewed. Route to AE for proposal scoping. The fourth gate (Q_TIMELINE_STATED) is still required before contract — this rule gates the discovery-to- proposal transition, not discovery-to-contract.


# --- Client HIL rules (from policy_overrides) ---
# HIL if: S_LINKEDIN_THOUGHT_LEADERSHIP_ENGAGEMENT AND Q_NEED_ARTICULATED AND confidence > 0.5
# Rationale: LinkedIn-inbound with articulated need: this is the boundary between AI tire-kicker and real buyer, and automated routing gets it wrong too often. Human review required to assess whether the articulated need is specific (business-contextualized problem) or vague (exploratory). Channel interview §2: "a vendor name, a specific failure mode, and a business context in the first message is almost always a buyer" — that specificity check requires human judgment. Route to founder or senior AE for 5-minute assessment. S_LINKEDIN_THOUGHT_LEADERSHIP_ENGAGEMENT is the custom signal defined in channel_overrides.yaml (add_to_schema: true), so it is a valid reference here.

# HIL if: Q_BUDGET_CONFIRMED AND Q_AUTHORITY_IDENTIFIED AND Q_TIMELINE_STATED is null
# Rationale: Budget and authority confirmed but no timeline = possible project not yet real. This combination appeared in 2 of 5 lost deals (L-4: budget cycle miss, L-2: CTO departure caused timing issue). Without a stated timeline, we cannot confirm that the project exists within the current budget cycle. HIL to probe: "Is this project specifically budgeted for Q[current], and who internally owns the timeline?"

# HIL if: A_EMPLOYEE_RANGE in ['51-200'] AND A_FUNDING_STAGE in ['series_b', 'series_c', 'series_d_plus']
# Rationale: Series B/C+ companies in the employee sweet spot: these are high-value but may have procurement friction (see Deal L-1, 300-employee Series C that went to a larger firm on credibility). HIL to assess: is there a procurement process? Does our team size create delivery risk perception? These prospects need a different close motion (more references, possibly a subcontractor structure).

